# blue deployment
apiVersion: apps/v1
kind: Deployment
metadata: { name: frontend-blue }
spec:
  replicas: 3
  selector: { matchLabels:{ app: finance-frontend, variant: blue } }
  template:
    metadata: { labels:{ app: finance-frontend, variant: blue } }
    spec:
      containers:
      - name: frontend
        image: ${ECR_REGISTRY}/finance-manager-frontend:${IMAGE_TAG}
        env:
        - name: FRONTEND_VERSION
          value: "${IMAGE_TAG}"
        ports: [{ containerPort: 3000 }]
---
# green deployment
apiVersion: apps/v1
kind: Deployment
metadata: { name: frontend-green }
spec:
  replicas: 3
  selector: { matchLabels:{ app: finance-frontend, variant: green } }
  template:
    metadata: { labels:{ app: finance-frontend, variant: green } }
    spec:
      containers:
      - name: frontend
        image: ${ECR_REGISTRY}/finance-manager-frontend:${IMAGE_TAG}
        env:
        - name: FRONTEND_VERSION
          value: "${IMAGE_TAG}"
        ports: [{ containerPort: 3000 }]
---
apiVersion: v1
kind: Service
metadata: { name: finance-frontend-svc }
spec:
  type: LoadBalancer
  ports: [{ port:80, targetPort:3000 }]
  selector:
    app: finance-frontend
    variant: blue   # default inbound
