# infra/.github/workflows/deploy.yml
name: Deploy to EKS (QA, UAT, Prod)

on:
  repository_dispatch:
    types: [qa_deploy, uat_promote, prod_promote]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init & Apply
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name fm-eks

      - name: Render & Apply Kustomize
        env:
          IMAGE_TAG: ${{ github.event.client_payload.tag }}
        run: |
          case "${{ github.event.action }}" in
            qa_deploy)    OVERLAY=overlays/qa ;;
            uat_promote)  OVERLAY=overlays/uat ;;
            prod_promote) OVERLAY=overlays/prod ;;
          esac

          # Substitute IMAGE_TAG into kustomize
          kubectl kustomize k8s/$OVERLAY \
            | sed "s|\${IMAGE_TAG}|${IMAGE_TAG}|g" \
            | kubectl apply -f -
